# Generated by Django 3.0.3 on 2020-09-17 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='entry_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
