# Generated by Django 3.0.3 on 2020-09-17 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_registration', '0002_auto_20200916_1915'),
        ('attendance', '0002_auto_20200916_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_student', to='class_registration.Student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_subject', to='class_registration.Subject'),
        ),
    ]
