# Generated by Django 3.0.3 on 2020-09-22 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20200916_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
