# Generated by Django 3.0.3 on 2020-09-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='attendance_date',
            field=models.DateField(),
        ),
    ]
