# Generated by Django 3.0.3 on 2020-09-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_registration', '0002_auto_20200916_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
