# Generated by Django 3.0.3 on 2020-09-22 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_registration', '0003_student_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fees',
        ),
        migrations.CreateModel(
            name='StudentFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Fees Added On')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='class_registration.Student')),
            ],
        ),
    ]
